### ISSUE TITLE
Curl command times out on page 29

### ISSUE THREAD

**Issue by dadreggors** [vfarcic/k8s-specs#10] opened 2018-08-22 20:47 UTC
I am trying the lesson "Creating Ingress Resources Based On Paths" and am on page 29. The curl command (curl -i "http://$IP/demo/hello") just times out. I have confirmed all is up and $IP is set with an ip address. I also confirmed that the "ingress" addon is enabled.

I have done a minikube delete twice now and copy/pasted the code. All works right up to this curl command which takes forever and just returns this finally...

> $ minikube addons list|grep ingress
> ingress: enabled
> $ IP=$(kubectl get ingress go-demo-2 \
> -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
> $ echo $IP
> 10.0.2.15
> $ curl -i "http://$IP/demo/hello"
> curl: (7) Failed to connect to 10.0.2.15 port 80: Connection timed out

I have pulled the latest changes as well...
> $ git pull
> Already up to date.

**Comment by dadreggors** [comment] 2018-08-22 21:00
It is also worth noting that a friend has the same issue, but says he was able to run this command a couple of days ago and after his latest pull it is now broken for him as well.

**Comment by vfarcic** [comment] 2018-08-22 21:15
I'll rerun the chapter tomorrow and get back to you. Too tired to do it now (it's around midnight where I live).

**Comment by psfleming** [comment] 2018-08-22 21:50
I think the issue is here on page 129:
Let’s see whether requests sent to the base path /demo work.
IP=$(kubectl get ingress go-demo-2 \
-o jsonpath="{.status.loadBalancer.ingress[0].ip}")

curl -i "http://$IP/demo/hello"

The IP variable is set to the 10.x.x.x of the ingress. Should IP be set to the minikube like
IP=$(minikube ip)

That seems to have worked for me. FYI, love the book!

**Comment by vfarcic** [comment] 2018-08-22 22:13
You're right. The IP should be from `minikube ip`, not from Ingress. In most other k8s flavors Ingress would create an external LB or open a port in an existing one. The IP of Ingress would be the IP of the LB. But, in case of minikube, there is no external LB so the IP is from the VM created by minikube.

Thanks for letting me know. The new version of the book will be released in a few min.

**Closed as completed by vfarcic** 2018-08-22 22:13 UTC
